language: python

dist: precise

python:
  - "3.6"

before_install:
  - "sudo apt-get install ghostscript"

install:
  - "pip install -r requirements.txt"
  - "pip install coveralls codecov"
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/app
script:
  - pytest --cov ./app
after_success:
  - coveralls
  - codecov -t bf8418dd-dd8c-4954-8e85-2f9b974e3566